import {
  mdiAirplane, mdiAlien, mdiAnchor, mdiApple, mdiAxeBattle, mdiBalloon,
  mdiBasketball, mdiBat, mdiBee, mdiBicycle, mdiBird, mdiBowArrow, mdiBridge,
  mdiButterfly, mdiCactus, mdiCamera, mdiCar, mdiCarrot, mdiCastle, mdiCat,
  mdiChessKnight, mdiClock, mdiCloud, mdiCompass, mdiCow, mdiCrown,
  mdiDiamondStone, mdiDog, mdiDolphin, mdiDuck, mdiEarth, mdiElephant, mdiEye,
  mdiFire, mdiFish, mdiFlower, mdiFlowerTulip, mdiFruitCherries, mdiGamepadVariant,
  mdiGhost, mdiGift, mdiGuitarAcoustic, mdiHeart, mdiHelicopter, mdiHome,
  mdiHorse, mdiJellyfish, mdiKangaroo, mdiKey, mdiKoala, mdiLadybug, mdiLamp,
  mdiLeaf, mdiLightbulb, mdiLighthouse, mdiMagicStaff, mdiMapMarker, mdiMedal,
  mdiMoonWaningCrescent, mdiMotorbike, mdiMushroom, mdiMusic, mdiOwl, mdiPanda,
  mdiPenguin, mdiPiano, mdiPig, mdiPineTree, mdiPuzzle, mdiRabbit, mdiRobot,
  mdiRocketLaunch, mdiRun, mdiSailBoat, mdiSatelliteVariant, mdiShark, mdiSheep,
  mdiShield, mdiShipWheel, mdiSkull, mdiSnail, mdiSnowflake, mdiSoccer, mdiSpider,
  mdiStarFourPoints, mdiSword, mdiTennis, mdiTent, mdiTrain, mdiTree, mdiTrophy,
  mdiTurtle, mdiUmbrella, mdiUnicorn, mdiViolin, mdiWater, mdiWeatherLightning,
  mdiWeatherSunny, mdiWindTurbine, mdiWizardHat,
} from "@mdi/js";

export type Level = { name: string; path: string; difficulty: 1 | 2 | 3 };

export const LEVELS: Level[] = [
  ["Бабочка", mdiButterfly], ["Птица", mdiBird], ["Кошка", mdiCat],
  ["Собака", mdiDog], ["Кролик", mdiRabbit], ["Рыба", mdiFish],
  ["Черепаха", mdiTurtle], ["Лошадь", mdiHorse], ["Слон", mdiElephant],
  ["Панда", mdiPanda], ["Сова", mdiOwl], ["Пчела", mdiBee],
  ["Божья коровка", mdiLadybug], ["Улитка", mdiSnail], ["Паук", mdiSpider],
  ["Летучая мышь", mdiBat], ["Дельфин", mdiDolphin], ["Медуза", mdiJellyfish],
  ["Акула", mdiShark], ["Пингвин", mdiPenguin], ["Утка", mdiDuck],
  ["Поросёнок", mdiPig], ["Корова", mdiCow], ["Овечка", mdiSheep],
  ["Коала", mdiKoala], ["Кенгуру", mdiKangaroo], ["Единорог", mdiUnicorn],
  ["Цветок", mdiFlower], ["Тюльпан", mdiFlowerTulip], ["Лист", mdiLeaf],
  ["Дерево", mdiTree], ["Сосна", mdiPineTree], ["Кактус", mdiCactus],
  ["Гриб", mdiMushroom], ["Вишни", mdiFruitCherries], ["Яблоко", mdiApple],
  ["Морковь", mdiCarrot], ["Полумесяц", mdiMoonWaningCrescent],
  ["Звезда", mdiStarFourPoints], ["Солнце", mdiWeatherSunny], ["Облако", mdiCloud],
  ["Молния", mdiWeatherLightning], ["Снежинка", mdiSnowflake], ["Огонь", mdiFire],
  ["Капля", mdiWater], ["Планета", mdiEarth], ["Ракета", mdiRocketLaunch],
  ["Спутник", mdiSatelliteVariant], ["Самолёт", mdiAirplane], ["Вертолёт", mdiHelicopter],
  ["Парусник", mdiSailBoat], ["Автомобиль", mdiCar], ["Мотоцикл", mdiMotorbike],
  ["Поезд", mdiTrain], ["Велосипед", mdiBicycle], ["Дом", mdiHome],
  ["Замок", mdiCastle], ["Мост", mdiBridge], ["Маяк", mdiLighthouse],
  ["Палатка", mdiTent], ["Ветряк", mdiWindTurbine], ["Ключ", mdiKey],
  ["Корона", mdiCrown], ["Алмаз", mdiDiamondStone], ["Сердце", mdiHeart],
  ["Музыка", mdiMusic], ["Гитара", mdiGuitarAcoustic], ["Скрипка", mdiViolin],
  ["Пианино", mdiPiano], ["Камера", mdiCamera], ["Геймпад", mdiGamepadVariant],
  ["Шахматный конь", mdiChessKnight], ["Пазл", mdiPuzzle], ["Воздушный шар", mdiBalloon],
  ["Подарок", mdiGift], ["Зонт", mdiUmbrella], ["Лампа", mdiLamp],
  ["Лампочка", mdiLightbulb], ["Часы", mdiClock], ["Компас", mdiCompass],
  ["Метка", mdiMapMarker], ["Якорь", mdiAnchor], ["Штурвал", mdiShipWheel],
  ["Меч", mdiSword], ["Щит", mdiShield], ["Лук", mdiBowArrow],
  ["Боевой топор", mdiAxeBattle], ["Волшебный посох", mdiMagicStaff],
  ["Шляпа волшебника", mdiWizardHat], ["Призрак", mdiGhost], ["Робот", mdiRobot],
  ["Пришелец", mdiAlien], ["Череп", mdiSkull], ["Глаз", mdiEye],
  ["Бег", mdiRun], ["Футбол", mdiSoccer], ["Баскетбол", mdiBasketball],
  ["Теннис", mdiTennis], ["Медаль", mdiMedal], ["Кубок", mdiTrophy],
].map(([name, path], index) => ({
  name,
  path,
  difficulty: (index < 30 ? 1 : index < 70 ? 2 : 3) as 1 | 2 | 3,
}));

export const TOTAL_LEVELS = LEVELS.length;
